//! Arc length and its inverse.
//!
//! The arc length of a Bezier segment is the integral of `|B'(t)|`, which has
//! no closed form for cubics -- the integrand is the square root of a quartic.
//! So it is integrated numerically, by Gauss-Legendre quadrature with adaptive
//! bisection.
//!
//! Gauss-Legendre is the right tool because `|B'(t)|` is analytic away from
//! cusps: an n-point rule is exact for polynomials of degree `2n-1`, so the
//! 8-point rule below nails a smooth segment to machine precision in a single
//! pass of eight derivative evaluations. Where the curve has a cusp `|B'|` has
//! a square-root kink, Gauss-Legendre stalls, and the adaptive bisection
//! recovers the accuracy by shrinking the panels around it.
//!
//! The inverse, [`CubicBez::t_at_length`], is what dash patterns and text on a
//! path are built from, so it runs in hot loops. It is a Newton iteration --
//! the derivative of arc length with respect to `t` is just `|B'(t)|`, free --
//! kept honest by a bisection bracket for the cusps and inflections where
//! Newton alone would wander.

use crate::{CubicBez, QuadBez};

/// Nodes and weights of the 8-point Gauss-Legendre rule on `[-1, 1]`.
///
/// The nodes are the roots of the Legendre polynomial `P_8` and the weights
/// are `2 / ((1 - x^2) P_8'(x)^2)`. Generated by Newton iteration on `P_8`;
/// they agree with Abramowitz & Stegun, Table 25.4, to all printed digits.
const GAUSS_LEGENDRE_8: [(f64, f64); 8] = [
    (-0.9602898564975363, 0.10122853629037618),
    (-0.7966664774136268, 0.22238103445337445),
    (-0.525532409916329, 0.3137066458778874),
    (-0.1834346424956498, 0.362683783378362),
    (0.1834346424956498, 0.362683783378362),
    (0.525532409916329, 0.3137066458778874),
    (0.7966664774136268, 0.22238103445337445),
    (0.9602898564975363, 0.10122853629037618),
];

/// Relative accuracy the adaptive bisection targets.
///
/// This bounds the *estimated* error of a single panel, and the value actually
/// returned is the two-half sum, which is roughly 2^9 times better again. Set
/// tighter and the panel count grows without the answer improving, because
/// f64 cancellation in the sum takes over.
const REL_TOL: f64 = 1e-12;

/// Bisection depth cap. A cusp is the only thing that gets near it, and 24
/// levels shrink a panel to 6e-8 of the original range -- past the point where
/// the remaining length is visible at any zoom.
const MAX_DEPTH: u32 = 24;

/// One 8-point Gauss-Legendre panel over `[a, b]`.
#[inline]
fn gauss8(f: &impl Fn(f64) -> f64, a: f64, b: f64) -> f64 {
    let half = 0.5 * (b - a);
    let mid = 0.5 * (a + b);
    let mut sum = 0.0;
    for (x, w) in GAUSS_LEGENDRE_8 {
        sum += w * f(mid + half * x);
    }
    half * sum
}

/// Adaptive bisection of a panel whose 8-point value is `whole`.
///
/// Compares the panel against the sum of its two halves; the difference is the
/// error estimate. Splitting the tolerance between the halves keeps the total
/// error bounded by `tol` regardless of how deep any one branch recurses.
fn adaptive(f: &impl Fn(f64) -> f64, a: f64, b: f64, whole: f64, tol: f64, depth: u32) -> f64 {
    let mid = 0.5 * (a + b);
    let left = gauss8(f, a, mid);
    let right = gauss8(f, mid, b);
    let sum = left + right;
    if depth == 0 || (sum - whole).abs() <= tol {
        return sum;
    }
    adaptive(f, a, mid, left, 0.5 * tol, depth - 1)
        + adaptive(f, mid, b, right, 0.5 * tol, depth - 1)
}

/// Arc length of `f = |B'|` over `[t0, t1]`.
fn integrate(f: impl Fn(f64) -> f64, t0: f64, t1: f64) -> f64 {
    let whole = gauss8(&f, t0, t1);
    // Relative, so the tolerance means the same thing for a 2px glyph stem and
    // a 20000px artboard diagonal. A degenerate segment gives whole == 0 and
    // terminates on the first comparison, 0 <= 0.
    adaptive(&f, t0, t1, whole, REL_TOL * whole, MAX_DEPTH)
}

/// Newton iteration cap. Convergence is quadratic and the bracket halves even
/// in the worst case, so this is only ever reached by a curve whose length is
/// flat to within an ulp over a whole interval.
const MAX_NEWTON: u32 = 64;

/// Safeguarded Newton solve of `length_at_t(t) == s`, given `0 < s < total`.
///
/// `len` is the arc length from 0 to `t` and `speed` is `|B'(t)|`, its exact
/// derivative. `t` is kept strictly inside a bracket that always contains the
/// root, so it can never reach 0 or 1 and the exact-endpoint guarantee in the
/// callers holds.
///
/// `len` re-integrates from 0 on every step, so one solve costs a few hundred
/// derivative evaluations. That is fine for a handful of dash boundaries per
/// segment; a dash pattern that walks thousands of stops along one curve wants
/// a cached table of `t` against length instead, built once per segment.
fn solve_t(len: impl Fn(f64) -> f64, speed: impl Fn(f64) -> f64, s: f64, total: f64) -> f64 {
    let tol = REL_TOL * total;
    let (mut lo, mut hi) = (0.0, 1.0);
    // Constant-speed guess. Exact for a straight line, and within a few
    // percent for anything a designer draws, which buys an iteration or two.
    let mut t = s / total;
    for _ in 0..MAX_NEWTON {
        let err = len(t) - s;
        if err.abs() <= tol {
            return t;
        }
        if err > 0.0 {
            hi = t
        } else {
            lo = t
        }
        let d = speed(t);
        let next = t - err / d;
        // Rejects NaN from a cusp's zero speed as well as any step that leaves
        // the bracket, which is what Newton does at an inflection.
        let next = if next > lo && next < hi {
            next
        } else {
            0.5 * (lo + hi)
        };
        if next == t {
            return t;
        }
        t = next;
    }
    t
}

impl CubicBez {
    /// Arc length from the start of the segment to parameter `t`.
    ///
    /// `length_at_t(1.0)` is the length of the whole segment.
    pub fn length_at_t(self, t: f64) -> f64 {
        integrate(|u| self.deriv_at(u).length(), 0.0, t)
    }

    /// The parameter `t` at arc length `s` from the start of the segment.
    ///
    /// The inverse of [`length_at_t`](Self::length_at_t). `s` is clamped to the
    /// segment: `t_at_length(0.0)` is exactly 0.0 and any `s` at or past the
    /// total length is exactly 1.0, so walking a path segment by segment lands
    /// on the shared endpoints bit-for-bit rather than a hair short.
    pub fn t_at_length(self, s: f64) -> f64 {
        // The NaN arm keeps a bad input at the start rather than letting it
        // fall through into the iteration.
        if s <= 0.0 || s.is_nan() {
            return 0.0;
        }
        let total = self.length_at_t(1.0);
        if s >= total {
            return 1.0;
        }
        solve_t(
            |t| self.length_at_t(t),
            |t| self.deriv_at(t).length(),
            s,
            total,
        )
    }
}

impl QuadBez {
    /// Arc length from the start of the segment to parameter `t`.
    ///
    /// `length_at_t(1.0)` is the length of the whole segment.
    pub fn length_at_t(self, t: f64) -> f64 {
        integrate(|u| self.deriv_at(u).length(), 0.0, t)
    }

    /// The parameter `t` at arc length `s` from the start of the segment.
    ///
    /// The inverse of [`length_at_t`](Self::length_at_t), with the same exact
    /// behaviour at the ends as [`CubicBez::t_at_length`].
    pub fn t_at_length(self, s: f64) -> f64 {
        if s <= 0.0 || s.is_nan() {
            return 0.0;
        }
        let total = self.length_at_t(1.0);
        if s >= total {
            return 1.0;
        }
        solve_t(
            |t| self.length_at_t(t),
            |t| self.deriv_at(t).length(),
            s,
            total,
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::Point;

    /// de Casteljau split at `t`, local to the tests so this module does not
    /// depend on `split.rs` landing first.
    fn split(c: CubicBez, t: f64) -> (CubicBez, CubicBez) {
        let a = c.p0.lerp(c.p1, t);
        let b = c.p1.lerp(c.p2, t);
        let d = c.p2.lerp(c.p3, t);
        let e = a.lerp(b, t);
        let f = b.lerp(d, t);
        let g = e.lerp(f, t);
        (CubicBez::new(c.p0, a, e, g), CubicBez::new(g, f, d, c.p3))
    }

    /// The cubic that approximates the unit-circle arc from `a0` to `a1`, with
    /// the classic `k = 4/3 tan(theta/4)` handle length.
    fn arc(a0: f64, a1: f64) -> CubicBez {
        let k = 4.0 / 3.0 * ((a1 - a0) / 4.0).tan();
        let (s0, c0) = a0.sin_cos();
        let (s1, c1) = a1.sin_cos();
        CubicBez::new(
            Point::new(c0, s0),
            Point::new(c0 - k * s0, s0 + k * c0),
            Point::new(c1 + k * s1, s1 - k * c1),
            Point::new(c1, s1),
        )
    }

    fn wiggly() -> CubicBez {
        CubicBez::new(
            Point::new(0.0, 0.0),
            Point::new(1.0, 2.0),
            Point::new(3.0, -1.0),
            Point::new(4.0, 1.0),
        )
    }

    #[test]
    fn straight_line_length_is_endpoint_distance() {
        // Evenly spaced collinear control points: a degree-3 straight line.
        let c = CubicBez::new(
            Point::new(1.0, 2.0),
            Point::new(3.0, 5.0),
            Point::new(5.0, 8.0),
            Point::new(7.0, 11.0),
        );
        let expected = (c.p3 - c.p0).length();
        assert!((c.length_at_t(1.0) - expected).abs() < 1e-9);

        // Unevenly spaced too: the path is the same segment, only the
        // parameterization is bunched, which is what the quadrature has to
        // absorb.
        let c = CubicBez::new(
            Point::new(0.0, 0.0),
            Point::new(0.1, 0.1),
            Point::new(0.2, 0.2),
            Point::new(3.0, 3.0),
        );
        assert!((c.length_at_t(1.0) - (c.p3 - c.p0).length()).abs() < 1e-9);
    }

    #[test]
    fn quarter_circle_matches_pi_over_two() {
        // A single cubic approximates a 90-degree arc only to 2.2e-4 in length,
        // which is the approximation's error and not the quadrature's. Four
        // 22.5-degree cubics bring it to 5e-8.
        let total: f64 = (0..4)
            .map(|i| {
                let step = core::f64::consts::FRAC_PI_2 / 4.0;
                arc(f64::from(i) * step, f64::from(i + 1) * step).length_at_t(1.0)
            })
            .sum();
        assert!((total - core::f64::consts::FRAC_PI_2).abs() < 1e-6);
    }

    #[test]
    fn quadrature_hits_a_known_value() {
        // The single-cubic quarter circle, integrated to 25 digits externally.
        // This pins the quadrature itself rather than the approximation.
        let l = arc(0.0, core::f64::consts::FRAC_PI_2).length_at_t(1.0);
        assert!((l - 1.5710166980738545).abs() < 1e-13, "{l}");
    }

    #[test]
    fn split_halves_sum_to_the_whole() {
        let c = wiggly();
        let whole = c.length_at_t(1.0);
        for i in 1..20 {
            let t = f64::from(i) / 20.0;
            let (a, b) = split(c, t);
            let sum = a.length_at_t(1.0) + b.length_at_t(1.0);
            assert!((sum - whole).abs() < 1e-9, "t={t} sum={sum} whole={whole}");
            // The parameter split has to agree with the geometric one.
            assert!(
                (c.length_at_t(t) - a.length_at_t(1.0)).abs() < 1e-9,
                "t={t}"
            );
        }
    }

    #[test]
    fn length_at_t_is_monotone_from_zero() {
        let c = wiggly();
        assert_eq!(c.length_at_t(0.0), 0.0);
        let mut prev = 0.0;
        for i in 1..=100 {
            let l = c.length_at_t(f64::from(i) / 100.0);
            assert!(l > prev, "i={i}");
            prev = l;
        }
    }

    #[test]
    fn t_at_length_inverts_length_at_t() {
        let curves = [
            wiggly(),
            arc(0.0, core::f64::consts::FRAC_PI_2),
            // A cusp: the derivative vanishes at t = 0.5, where Newton has
            // nothing to divide by and the bracket has to carry the solve.
            CubicBez::new(
                Point::new(0.0, 0.0),
                Point::new(1.0, 1.0),
                Point::new(-1.0, 1.0),
                Point::new(0.0, 0.0),
            ),
        ];
        for c in curves {
            let total = c.length_at_t(1.0);
            for i in 0..=200 {
                let s = total * f64::from(i) / 200.0;
                let t = c.t_at_length(s);
                assert!((c.length_at_t(t) - s).abs() < 1e-9, "s={s} t={t}");
            }
        }
    }

    #[test]
    fn t_at_length_is_exact_at_the_ends() {
        let c = wiggly();
        let total = c.length_at_t(1.0);
        assert_eq!(c.t_at_length(0.0), 0.0);
        assert_eq!(c.t_at_length(total), 1.0);
        // Out of range in both directions clamps rather than extrapolating.
        assert_eq!(c.t_at_length(-5.0), 0.0);
        assert_eq!(c.t_at_length(total * 2.0), 1.0);
        assert_eq!(c.t_at_length(f64::NAN), 0.0);
        assert_eq!(c.t_at_length(f64::INFINITY), 1.0);
    }

    #[test]
    fn degenerate_curve_has_zero_length() {
        let p = Point::new(2.0, 3.0);
        let c = CubicBez::new(p, p, p, p);
        assert_eq!(c.length_at_t(1.0), 0.0);
        assert_eq!(c.t_at_length(0.0), 0.0);
        assert_eq!(c.t_at_length(1.0), 1.0);
    }

    #[test]
    fn quad_agrees_with_its_cubic() {
        let q = QuadBez::new(
            Point::new(0.0, 0.0),
            Point::new(3.0, 6.0),
            Point::new(9.0, 0.0),
        );
        let c = q.to_cubic();
        assert!((q.length_at_t(1.0) - c.length_at_t(1.0)).abs() < 1e-9);
        let total = q.length_at_t(1.0);
        for i in 0..=20 {
            let s = total * f64::from(i) / 20.0;
            let t = q.t_at_length(s);
            assert!((q.length_at_t(t) - s).abs() < 1e-9, "s={s}");
        }
        assert_eq!(q.t_at_length(0.0), 0.0);
        assert_eq!(q.t_at_length(total), 1.0);
    }

    #[test]
    fn tiny_and_huge_segments_keep_relative_accuracy() {
        // The tolerance is relative, so a glyph-scale and an artboard-scale
        // copy of the same shape must both come out to the same ratio.
        let c = wiggly();
        let base = c.length_at_t(1.0);
        for scale in [1e-6, 1e6] {
            let s = CubicBez::new(
                Point::new(c.p0.x * scale, c.p0.y * scale),
                Point::new(c.p1.x * scale, c.p1.y * scale),
                Point::new(c.p2.x * scale, c.p2.y * scale),
                Point::new(c.p3.x * scale, c.p3.y * scale),
            );
            let rel = (s.length_at_t(1.0) / scale - base).abs() / base;
            assert!(rel < 1e-12, "scale={scale} rel={rel}");
        }
    }
}
